### ISSUE TITLE
Reload watcher when webpack.mix.js file is udpdated

### ISSUE THREAD

**Issue by anewage** [fandogh/laravel-multimix#1]
Not sure if this is a relative issue, but there isn't so much of a change when the `webpack.mix.js` file is updated while the `run watch <package name>` is executing (changes in the webpack file are of course in the scope of the requested package!). So you have to stop the execution of that command, make the changes to webpack file and run it again to see the changes.

Again, not sure if this is an appropriate question or the webpack is technically not meant to change or update during watch operation.

**Comment by pi0** [comment]
Hey @anewage to achive this you can install nodemon : 
```npm install -g nodemon```
Then watch for changes: ```nodemon --watch webpack.mix.js node_modules/.bin/laravel-multimix watch```

This can also be easily added to workflow by:
- adding nodemon to project devDependencies
- add a line like this : 
```js
"mix": "nodemon --watch webpack.mix.js node_modules/.bin/laravel-multimix"
```

**Comment by the94air** [comment]
For some reason `nodemon` didn't work until I removed the last `watch`
```json
"scripts": {
    "mix": "nodemon --watch webpack.mix.js node_modules/.bin/laravel-multimix"
}
```
